EmployeeRecordMgmt/urls.py
from django.contrib import admin
from django.urls import path, include
from employee import views
from django.contrib.auth import views as auth_views
from time_tracker.views import time_tracker, save_time_data_view, show_time_data
#from employee.views import TaskList, TaskDetail, TaskCreate, TaskUpdate, DeleteView, TaskReorder
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('forgotpass/', views.ForgotPass, name='forgotpass'),
    path('signup/',views.SignupPage,name='signup'),
    path('login/',views.LoginPage,name='login'),

    path('delete/<int:id>/',views.DeleteData, name='deleteData'),
     path('employees/',views.EmpPage, name='employees'),
      path('<int:id>/',views.UpdateEmp, name='updateData'),
      path('addEmp/',views.AddEmp, name='addEmp'),
     # path('inactiveEmp/',views.InactiveEmp, name='inactiveEmp'),
      
    path('',views.HomePage, name='home'),
    path('logout/',views.LogoutPage,name='logout'),
    path('teamheadlogout/',views.TeamHeadLogout,name='teamheadlogout'),
    #path('admin/', views.admin,name='admin'),
    path('adminhome/', views.AdminHomePage, name='adminhome'),
    path('teamheadregister/', views.TeamHeadRegister, name='teamheadregister'),
    path('teamheadlogin/', views.TeamHeadLogin, name='teamheadlogin'),
    path('teamheadhome/', views.TeamHeadHome, name='teamheadhome'),
    path('teammemhome/', views.TeamMemHome, name='teammemhome'),
    
    path('projectcreate/', views.CreateProject, name='projectcreate'),
    path('projectlist/', views.ProjectList, name='projectlist'),
    path('adminproject/', views.AdminProject, name='adminproject'),
    path('memtasklist/', views.MemTaskList, name='memtasklist'),
    path('addUser/', views.addUser, name='addUser'),
    path('teammemlogin/', views.TeamMemLogin, name='teammemlogin'),
    path('teammemregister/', views.TeamMemRegister, name='teammemregister'),
    #path('projectdetail<int:id>/',ProjectDetail.as_view(), name='projdetail'),
    path('todo/', views.TaskListabc, name='todo'),
    #path('main/', views.Main, name='main'),
    path('task_list/', views.ProList, name='task_list'),
    
    path('reset_password/', 
         auth_views.PasswordResetView.as_view(template_name="password_reset.html"), 
         name="reset_password"),
    
    path('reset_password_sent/', 
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), 
         name="password_reset_done"),
    
    path('reset/<uidb64>/<token>', 
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), 
         name="password_reset_confirm"),
    
    path('reset_password_complete/', 
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), 
         name="password_reset_complete"),
    
    path('time-tracker/', time_tracker, name='time_tracker'),
    path('save-data/', save_time_data_view, name='save_data'),
    path('time-data/', show_time_data, name='time_data'),
    
    path('delete/',views.DeleteTaskData, name='deleteTaskData'),
    path('tasklist/',views.TaskPage, name='tasklist'),
    path('',views.UpdateTaskData, name='updateTaskData'),
    path('addTaskData/',views.AddTask, name='addTaskData'),
#     path('home',home,name=home)
    # CREATE PROJECT
    #path('', TaskList.as_view(), name='tasks'),
    #path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    #path('task-create/', TaskCreate.as_view(), name='task-create'),
    #path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    #path('task-delete/<int:pk>/', DeleteView.as_view(), name='task-delete'),
    #path('task-reorder/', TaskReorder.as_view(), name='task-reorder'),
    #path('', include('base.urls')),
    
] 

admin.site.index_title = "DjangoNauts"
admin.site.site_header = "DjangoNauts Admin"

customadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', admin_login, name="admin_login"),
    
]

employee/templates/urls.py
from django.contrib import admin
from django.urls import path, include
from employee import views
from django.contrib.auth import views as auth_views
#from employee.views import TaskList, TaskDetail, TaskCreate, TaskUpdate, DeleteView, TaskReorder
from time_tracker.views import time_tracker, save_time_data_view, show_time_data


urlpatterns = [
    #path('', views.index, name='index'), 
    #path('all_events/', views.all_events, name='all_events'), 
    #path('add_event/', views.add_event, name='add_event'), 
    #path('update/', views.update, name='update'),
    #path('remove/', views.remove, name='remove'),
    
    path('admin/', admin.site.urls),
    path('forgotpass/', views.ForgotPass, name='forgotpass'),
    path('signup/',views.SignupPage,name='signup'),
    path('login/',views.LoginPage,name='login'),

    path('delete/<int:id>/',views.DeleteData, name='deleteData'),
     path('employees/',views.EmpPage, name='employees'),
      path('<int:id>/',views.UpdateEmp, name='updateData'),
      path('addEmp/',views.AddEmp, name='addEmp'),
     # path('inactiveEmp/',views.InactiveEmp, name='inactiveEmp'),
      
    path('',views.HomePage, name='home'),
    path('logout/',views.LogoutPage,name='logout'),
    path('teamheadlogout/',views.TeamHeadLogout,name='teamheadlogout'),
    #path('admin/', views.admin,name='admin'),
    path('adminhome/', views.AdminHomePage, name='adminhome'),
    path('teamheadregister/', views.TeamHeadRegister, name='teamheadregister'),
    path('teamheadlogin/', views.TeamHeadLogin, name='teamheadlogin'),
    path('teamheadhome/', views.TeamHeadHome, name='teamheadhome'),
    path('teammemlogin/', views.TeamMemLogin, name='teammemlogin'),
    path('addUser/', views.addUser, name='addUser'),
    path('teammemlogin/', views.TeamMemLogin, name='teammemlogin'),
    path('todo/', views.TaskListabc, name='todo'),
    #path('main/', views.Main, name='main'),
    path('task_list/', views.ProList, name='task_list'),
    
    path('reset_password/', 
         auth_views.PasswordResetView.as_view(template_name="password_reset.html"), 
         name="reset_password"),
    
    path('reset_password_sent/', 
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), 
         name="password_reset_done"),
    
    path('reset/<uidb64>/<token>', 
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), 
         name="password_reset_confirm"),
    
    path('reset_password_complete/', 
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), 
         name="password_reset_complete"),
#     path('home',home,name=home)

    path('time-tracker/', time_tracker, name='time_tracker'),
    path('save-data/', save_time_data_view, name='save_data'),
    path('time-data/', show_time_data, name='time_data'),
    
    path('projectcreate/', views.CreateProject, name='projectcreate'),
    path('projectlist/', views.ProjectList, name='projectlist'),
    path('adminproject/', views.AdminProject, name='adminproject'),
    
    path('delete/<int:name>/',views.DeleteTask, name='deleteTask'),
    path('tasks/',views.TaskPage, name='tasks'),
    path('<int:name>/',views.UpdateTask, name='updateTask'),
    path('addTask/',views.AddTask, name='addTask'),

    
]

admin.site.index_title = "DjangoNauts"
admin.site.site_header = "DjangoNauts Admin"

employee/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    role=[
        ('team member','Team Member'),
        ('team head','Team Head'),
        ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True,)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    address = models.CharField(max_length=200, null=True)
    role = models.CharField(max_length=50,choices=role,default="team Members")
    

    def __str__(self):
        return self.name 

class Employees(models.Model):
    #user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)#
    role=[
        ('team member','Team Member'),
        ('team head','Team Head'),
        ]
    empid = models.CharField(max_length=100)
    name = models.CharField(max_length=200)
    job = models.CharField(max_length=200)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=10)
    role = models.CharField(max_length=50,choices=role,default="team Members")
    
    def __str__(self):
        return self.name
    

class Project(models.Model):
       # emp = models.ForeignKey(Employees, on_delete=models.CASCADE, null=True)
    ptitle = models.CharField(max_length=100)
    pdesc = models.CharField(max_length=200)
    
    def __str__(self):
        return self.ptitle


class Task(models.Model):
    status=[
        ('Started','Started'),
        ('In Progress','In Progress'),
        ('Completed','Completed'),
        ]
    
    ptitle = models.OneToOneField(Project,on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    status = models.CharField(max_length=50,choices=status,default="In Progress")
    


    

employee/forms.py
from .models import Employees,Project,Profile, Task
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class EmployeeRegistration(forms.ModelForm):
    
    class Meta:
        model = Employees
        fields = ["empid","name","job","email","phone","role"]
        widgets = {
            'empid' : forms.TextInput(attrs={'class':'form-control'}),
            'name'  : forms.TextInput(attrs={'class':'form-control'}),
            'job'   : forms.TextInput(attrs={'class':'form-control'}),
            'email' : forms.EmailInput(attrs={'class':'form-control'}),
            'phone' : forms.TextInput(attrs={'class':'form-control'}),
        }


class profileForm(forms.ModelForm):
    class Meta:
        model = Profile
        
        fields = ['name', 'email', 'address', 'role']
        
#The labels attribute is optional. It is used to define the labels of the form fields created   
      #  labels = {
      #          "name":("Name     "),
       #         "email":("Email Address"),
       #         "address":("Street Address"),
       #         }
        
        widgets = {
            
            'name'  : forms.TextInput(attrs={'class':'form-control'}),  
            'email' : forms.EmailInput(attrs={'class':'form-control'}),
            'address' : forms.TextInput(attrs={'class':'form-control'}),
        }


class CreteUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        widgets = {
            
            'username'  : forms.TextInput(attrs={'class':'form-control'}),  
             'email' : forms.EmailInput(attrs={'class':'form-control'}),
            'password1' : forms.PasswordInput(attrs={'class':'form-control'}),
            'password2' : forms.PasswordInput(attrs={'class':'form-control'}),
            
            
        }
        
class ProjectCrete(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['ptitle','pdesc', 'name']
        widgets = {
            'ptitle' : forms.TextInput(attrs={'class':'form-control'}),
            'pdesc'  : forms.TextInput(attrs={'class':'form-control'}),
            
        }
        

class TaskCreate(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['ptitle', 'name', 'status']
        widgets = {
            'ptitle' : forms.TextInput(attrs={'class':'form-control'}),
            'name'  : forms.TextInput(attrs={'class':'form-control'}),
        
        }

employee/templates/TeamHbase.html
{% include "teamHheader.html" %}
{% load static %}
  <body>
   <div class="container mt-5">
   
    {%block content%}

    {%endblock content%}
   </div>
  <body>
    
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    
    <script src="{% static 'bootstrap/js/jquery.js' %}"></script>
    <script src="{% static 'bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
  </body>
  </html>

employee/templates/addEmp.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-6 offset-3">
     <h2 class ="text-center alert alert-info">Add Employee</h2>
     <form action="" method="POST">
       {% csrf_token %}
       {{form.as_p}}
       <input type="submit" class="btn btn-success" value="Add">
       <a href = "{% url 'employees' %}" class="btn btn-danger">Cancel</a>
     </form>
    </div>
</div>



{% endblock content %}

employee/templates/addTaskData.html
{% extends 'TeamHbase.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-6 offset-3">
     <h2 class ="text-center alert alert-info">Add Task</h2>
     <form action="" method="POST">
       {% csrf_token %}
       {{form.as_p}}
       <input type="submit" class="btn btn-success" value="Add">
       <a href = "{% url 'tasklist' %}" class="btn btn-danger">Cancel</a>
     </form>
    </div>
</div>



{% endblock content %}

employee/templates/adminproject.html
{% extends 'base.html' %}
{% block content %}
<style>
    #container{
    margin:20px;
      
    }
    .container{
        margin:20px;
    }
     
      #card{
          width:100%;
          height:100%;
          padding:20px;
      }
     
      /* Create two equal columns that floats next to each other */
  .column {
    float: left;
    width: 30%;
    padding: 10px;
    
  }
  
  /* Clear floats after the columns */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }
      
      
  </style>
  <div id="container">
        <div class="w3-container">
          <div id="card" class="w3-panel w3-card">
            <h3 class="card-title">Projects</h3>
            <!--div class="col-sm-11 offset-10"><a href = "{% url 'projectcreate' %}" > <button type="button" class="btn btn-success btn-defalut">Add Project</button></a> </div-->
          </div>
          
          
           
        </div>
        <hr style="margin:18px; height:2px; width:97%; border-width:0; background-color:black">



  
    
   
<div class="row"><div class="col-sm-11">

    
      <div class="w3-container">
      <div class="row">
        {% for p in projects %}
        <div class="column">
            <div id="card" class="w3-panel w3-card"><h3 class="card-title">{{ p.ptitle }}</h3>
            <hr style="height:2px; width:97%; border-width:0;  background-color:black">
            <div class="card-body">
                <p class="card-text" style="bottom-margin:20px">{{ p.pdesc }}</p>
                <!--a href="#" class="btn btn-primary stretched-link">Edit</a--></div>
                <!--a href="{{ p.affiliate_url }}" class="btn btn-warning">Buy now</a-->
            </div>
        </div>   
        {% endfor %}
      </div>
    </div>
</div></div>


{% endblock content %}

employee/templates/base.html
{% include "header.html" %}
{% load static %}
  <body>
   <div class="container mt-5">
   
    {%block content%}

    {%endblock content%}
   </div>
  <body>
    
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    
    <script src="{% static 'bootstrap/js/jquery.js' %}"></script>
    <script src="{% static 'bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
  </body>
  </html>

employee/templates/createproject.html
{% extends 'TeamHbase.html' %}
{% block content %}
<center>

</center>
<br>



{% endblock content %}

employee/templates/employees.html
{% extends 'base.html' %}
{% load static %}



 <!--div class="col-sm-4 offset-1">
  <h2 class ="text-center alert alert-info">Add Emp</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="Add">
  </form>


  <br><br><br>
    <h2 class ="text-center alert alert-info">Show Emp</h2>

 </div-->{% block content %}
 <style>
    .row{
        margin-block: 25px;
        margin-right:20px;
       
    }
    table {
        background-image: url('{% static 'images/profile.jpeg'%}');
        
    }
 </style>
 <div class="row"><div class="col-sm-11 offset-1">
    <a href = "{% url 'addUser' %}" ><button type="button" class="btn btn-success btn-defalut">Add Employee</button></a>
</div></div>
 
    
<!--div class="row"><div class="col-sm-11 offset-1">
    <a href = "{% url 'addEmp' %}" ><button type="button" class="btn btn-success btn-defalut">Add Employee</button></a>
</div></div-->


    <div class="row">
        <div class="col-sm-7 offset-1">
           
            <h2 class ="text-center alert alert-info" style="width:900px;">Employee List</h2>
           
     
        {% if em %}
         <table class="table table-hover" style="color:white; width:900px; height:400px;">
             <thead>
             <tr>
                 <!--th scope="col">ID</th-->
                 <th scope="col">Name</th>
                 <th scope="col">Username</th>
                 <th scope="col">Email</th>
                 <th scope="col">Address</th>
                 <th scope="col">Role</th>
                 <!--th scope="col">Role</th-->
                 <th scope="col">Action</th>
             </tr>
             </thead>
             <tbody>
                 {% for e in em %}
             <tr>
                 <!--th scope="row">{{e.empid}}</th-->
                 <td>{{e.name}}</td>
                 <td>{{e.username}}</td>
                 <td>{{e.email}}</td>
                 <td>{{e.address}}</td>
                 <td>{{e.role}}</td>
                 <!--td>{{e.role}}</td-->
                 
                 <td>
                     <a href="{% url 'updateData' e.id %}" class="btn btn-warning btn-sm">Edit</a>
                     <form action="{% url 'deleteData' e.id %}" method="POST" class="d-inline">
                         {% csrf_token %}
                         <input type="submit" class="btn btn-danger" value="Delete">
                     </form>
                 </td>
             </tr>
             {% endfor %}
             </tbody>
         </table>
    {%else %}
    <h4 class="text-center alert alert-warning">No Records</h4>
    {% endif %}
 
 
 
</div>
 
</div>
{% endblock content %}

employee/templates/forgotpass.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Forgot Password</title>
 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-image: url('{% static 'images/background.jpeg'%}');
    background-repeat:no repeat;
    background-position:top;
    background-size:1600px 750px;
    background-attachment:fixed;
}


form{
    height: 360px;
    width: 450px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 70%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
    float:right;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    background-color: rgba(255,255,255,-0.1);
    height: 40px;
    border:none;
    border-bottom: 1px solid white;
    outline: none;
    width: 100%;
    padding: 0 10px;
    margin-top: 2px;
    font-size: 14px;
    font-weight: 300;
}   
    
::placeholder{
    font-size: 1.2em;
    color: #FFFFFF;
}
button{
    margin-top: 14px;
    width: 50%;
    background-color:#FFBF00;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
img {
    border-radius: 4px;
    padding: 5px;
    width: 178px;
    height: auto;
  }


    </style>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %} 
        <h3>Forgot Password</h3><br>

        <label for="username"></label>
        <input type="text" placeholder="Username" name="username" id="username">

        <br><br><br><button type="submit" style="float: right;">Continue</button>
    </form>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<img src="https://www.linkpicture.com/q/Asset.png" alt="img1"><br>
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<img src="https://www.linkpicture.com/q/innovaton.png" alt="img">
    
</body>
</html>

employee/templates/memtasklist.html
{% extends 'TeamMbase.html' %}




 <!--div class="col-sm-4 offset-1">
  <h2 class ="text-center alert alert-info">Add Emp</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="Add">
  </form>


  <br><br><br>
    <h2 class ="text-center alert alert-info">Show Emp</h2>

 </div-->{% block content %}
 <style>
    .row{
        margin-block: 25px;
        margin-right:20px;
       
    }
 </style>
 
 
    



    <div class="row">
        <div class="col-sm-7 offset-1">
           
            <h2 class ="text-center alert alert-info">Task List</h2>
           
     
        {% if ts %}
         <table class="table table-hover">
             <thead>
             <tr>
                <th>
                 <th scope="col">Project Title</th>
                 <th scope="col">Name</th>
                 <th scope="col">Status</th>
             </tr>
             </thead>
             <tbody>
                 {% for t in ts %}
             <tr>
                <td>{{t.ser}}</td>
                 <td>{{t.ptitle}}</td>
                 <td>{{t.name}}</td>
                 <td>{{t.status}}</td>
                 
                
                 <td>
                     <a href="{% url 'updateTaskData' %}" class="btn btn-warning btn-sm">Edit</a>
                     <form action="{% url 'deleteTaskData' %}" method="POST" class="d-inline">
                         {% csrf_token %}
                         <input type="submit" class="btn btn-danger" value="Delete">
                     </form>
                 </td>
             </tr>
             {% endfor %}
             </tbody>
         </table>
    {%else %}
    <h4 class="text-center alert alert-warning">No Records</h4>
    {% endif %}
 
 
 
</div>
 
</div>
{% endblock content %}

employee/templates/project_detail.html
{% extends 'TeamHbase.html' %}
{% block content %}

<body>
	<h1>{{person.name}}'s Tasks</h1>
	<form method="post" action="">
		{% csrf_token %}
		{% for x in person.task_set.all %}
			{% if x.is_complete == True %}
				<input type="checkbox" value="clicked" name="t{{x.id}}" checked>{{x}}
			{% else %}
				<button type="submit" name="save" value="save"><input type="checkbox" value="clicked" name="t{{x.id}}"></button>{{x}}
			{% endif %}
			<button type="submit" name="save" value="save">SAVE CHANGES</button>
			<button type="submit" name="delete_this" value={{x.id}}>DELETE</button><br>
		{% endfor %}
	</form>
	<form method="post" action="">
		{% csrf_token %}
		<input type="textbox" name="new_item" placeholder="Enter Task...">
		<button type="submit" name="add_item" value="add_item">Add Item</button>
	</form>
    {% endblock content %}

employee/templates/projectlist.html
{% extends 'TeamHbase.html' %}
{% block content %}
<style>
    #container{
    margin:20px;
      
    }
    .container{
        margin:20px;
    }
     
      #card{
          width:100%;
          height:100%;
          padding:20px;
      }
     
      /* Create two equal columns that floats next to each other */
  .column {
    float: left;
    width: 30%;
    padding: 10px;
    
  }
  
  /* Clear floats after the columns */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }
      
      
  </style>
  <div id="container">
        <div class="w3-container">
          <div id="card" class="w3-panel w3-card">
            <h3 class="card-title">Projects</h3>
            <!--div class="col-sm-11 offset-10"><a href = "{% url 'projectcreate' %}" > <button type="button" class="btn btn-success btn-defalut">Add Project</button></a> </div-->
          </div>
          
          
           
        </div>
        <hr style="margin:18px; height:2px; width:97%; border-width:0; background-color:black">



  
    
   
<div class="row"><div class="col-sm-11">

    
      <div class="w3-container">
      <div class="row">
        {% for p in projects %}
        <div class="column">
            <div id="card" class="w3-panel w3-card"><h3 class="card-title">{{ p.ptitle }}</h3>
            <hr style="height:2px; width:97%; border-width:0;  background-color:black">
            <div class="card-body">
                <p class="card-text" style="bottom-margin:20px">{{ p.pdesc }}</p>
                <p class="card-text" style="bottom-margin:20px">{{ p.name }}</p>
                <a href="#" class="btn btn-primary stretched-link">Edit</a></div>
                <!--a href="{{ p.affiliate_url }}" class="btn btn-warning">Buy now</a-->
            </div>
        </div>   
        {% endfor %}
      </div>
    </div>
</div></div>


{% endblock content %}